excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://BDBargain.github.io
title: BDBargain
email: bdbargain2016@gmail.com
author: BDBargain
description: My awesome new site
paginate: 7
google_analytics: 